[build]
command = "pnpm run docs:build"
publish = ".xyd/build/client"

[[redirects]]
from = "/"
to = "/docs/getting-started/overview"
status = 301
force = true

[[redirects]]
from = "/index.html"
to = "/docs/getting-started/overview"
status = 301
force = true
